spring:
  application:
    name: operador-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
eureka:
  client:
    service-url:
      defaultZone: http://bibliotecaback-eureka-production.up.railway.app/eureka/
#      defaultZone: http://eureka-service-container:8761/eureka/
server:
  port: 8081
